### ISSUE TITLE
[02] Todo

### ISSUE THREAD

**Issue by jikkujose** [anandjos/storybrain-internship#3]
- [x] Create a simple todo app
- [x] Add, edit, remove items is required
- [x] Should be possible to add the app as PWA (an application that's optimised to work as a Home Screen app)

**Comment by jikkujose** [comment]
- [ ] Make data persistant using local storage
- [ ] Make color theme switch based on user preference
- [ ] Add checkbox to signify done/todo
